version: '3.9'

services:
  javanautadb:
    image: postgres:16
    container_name: fakeapi
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - javanauta_db:/var/lib/postgresql/data

volumes:
  javanauta_db:
    driver: local